/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.atticoos.tiokhttp;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.TiConfig;


@Kroll.module(name="TitaniumOkhttp", id="com.atticoos.tiokhttp")
public class TitaniumOkhttpModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TitaniumOkhttpModule";

	public TitaniumOkhttpModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) { }
}
